-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SESSION_ACCEPTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SESSION_DECLINED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'EXERCISE_ASSIGNED';
